### ISSUE TITLE
Android V2 Embedding

### ISSUE THREAD

**Issue by devSumanrazz** [deadblit/barras#19]
The plugins `qrcode, torch_compat` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.

**Comment by deadblit** [comment]
In the next release we won't use the `torch_compat` plugin anymore. You can target directly the branch `@r0.1.0-nullsafety.2` if you have problems with the current release.
