### ISSUE TITLE
Execution failed for task ':qrcode_forked:compileDebugKotlin'.

### ISSUE THREAD

**Issue by scorpioRED** [deadblit/barras#20]
Hi! Try to add barras dependency as:

  barras:
    git:
      url: https://github.com/deadblit/barras.git
      ref: r0.1.0-nullsafety.2

However, got an error when trying to lunch the app

![Screenshot 2022-10-12 at 13 46 55](https://user-images.githubusercontent.com/12165650/195324313-b72dc778-5ca1-4d91-a072-8cd6c3c6888c.png)

**Comment by deadblit** [comment]
Fixed in #22
